In [7]:
import pandas
import os
os.listdir('./data')

['supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [15]:
df_commas = pandas.read_csv('./data/supermarkets-commas.txt')
df_commas.set_index('ID')

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [16]:
df_json = pandas.read_json('./data/supermarkets.json')
df_json.set_index('ID')

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [20]:
df_xls = pandas.read_excel('./data/supermarkets.xlsx', sheetname=0)
df_xls

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [22]:
df_colons =pandas.read_csv('./data/supermarkets-semi-colons.txt', sep=';')
df_colons

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [23]:
df_url = pandas.read_csv('http://pythonhow.com/supermarkets.csv')
df_url

ID          Address            City             State Country  \
0   1     3666 21st St   San Francisco          CA 94114     USA   
1   2   735 Dolores St   San Francisco          CA 94119     USA   
2   3      332 Hill St   San Francisco  California 94114     USA   
3   4     3995 23rd St   San Francisco          CA 94114     USA   
4   5  1056 Sanchez St   San Francisco        California     USA   
5   6  551 Alvarado St   San Francisco          CA 94114     USA   

           Name  Employees  
0       Madeira          8  
1   Bready Shop         15  
2   Super River         25  
3    Ben's Shop         10  
4       Sanchez         12  
5    Richvalley         20

In [3]:
df_json = pandas.read_json('./data/supermarkets.json')


NameError: name 'pandas' is not defined

In [ ]:
print('hello'0)

In [2]:
print('hello')

hello


In [4]:
import pandas

In [5]:
df_json = pandas.read_json('./data/supermarkets.json')

In [6]:
df_json

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [9]:
df_addresss = df_json.set_index('Address')

In [10]:
df_addresss

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [11]:
mydf = df_addresss


In [12]:
mydf.loc['735 Dolores St':'332 Hill St', 'Country':'Id']

Country  Employees  ID
Address                              
735 Dolores St     USA         15   2
332 Hill St        USA         25   3

In [16]:
mydf.iloc[1,1:5]

Country              USA
Employees             15
ID                     2
Name         Bready Shop
Name: 735 Dolores St, dtype: object

In [17]:
mydf.ix[3,'Name']

"Ben's Shop"

In [19]:
mydf.drop('City',1)

Country  Employees  ID         Name             State
Address                                                              
3666 21st St        USA          8   1      Madeira          CA 94114
735 Dolores St      USA         15   2  Bready Shop          CA 94119
332 Hill St         USA         25   3  Super River  California 94114
3995 23rd St        USA         10   4   Ben's Shop          CA 94114
1056 Sanchez St     USA         12   5      Sanchez        California
551 Alvarado St     USA         20   6   Richvalley          CA 94114

In [20]:
mydf.drop(mydf.index[0:3], 0)

City Country  Employees  ID        Name       State
Address                                                                      
3995 23rd St     San Francisco     USA         10   4  Ben's Shop    CA 94114
1056 Sanchez St  San Francisco     USA         12   5     Sanchez  California
551 Alvarado St  San Francisco     USA         20   6  Richvalley    CA 94114

In [21]:
mydf.columns


Index(['City', 'Country', 'Employees', 'ID', 'Name', 'State'], dtype='object')

In [23]:
mydf['Continent'] = mydf.shape[0]*['North Maerica']

In [24]:
mydf

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State      Continent  
Address                                           
3666 21st St             CA 94114  North Maerica  
735 Dolores St           CA 94119  North Maerica  
332 Hill St      California 94114  North Maerica  
3995 23rd St             CA 94114  North Maerica  
1056 Sanchez St        California  North Maerica  
551 Alvarado St          CA 94114  North Maerica

In [25]:
mydf.shape


(6, 7)

In [26]:
mydf.shape[0]*['chad']

['chad', 'chad', 'chad', 'chad', 'chad', 'chad']

In [27]:
mydf

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State      Continent  
Address                                           
3666 21st St             CA 94114  North Maerica  
735 Dolores St           CA 94119  North Maerica  
332 Hill St      California 94114  North Maerica  
3995 23rd St             CA 94114  North Maerica  
1056 Sanchez St        California  North Maerica  
551 Alvarado St          CA 94114  North Maerica

In [28]:
mydf_t = mydf.T


In [29]:
mydf_t


Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
City       San Francisco  San Francisco     San Francisco  San Francisco   
Country              USA            USA               USA            USA   
Employees              8             15                25             10   
ID                     1              2                 3              4   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
State           CA 94114       CA 94119  California 94114       CA 94114   
Continent  North Maerica  North Maerica     North Maerica  North Maerica   

Address   1056 Sanchez St 551 Alvarado St  
City        San Francisco   San Francisco  
Country               USA             USA  
Employees              12              20  
ID                      5               6  
Name              Sanchez      Richvalley  
State          California        CA 94114  
Continent   North Maerica   North Maerica

In [30]:
mydf_t['My address'] = ['My City', 'My  Country', 10,7,'My Shop', 'My State', 'Content']

In [31]:
mydf_t


Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
City       San Francisco  San Francisco     San Francisco  San Francisco   
Country              USA            USA               USA            USA   
Employees              8             15                25             10   
ID                     1              2                 3              4   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
State           CA 94114       CA 94119  California 94114       CA 94114   
Continent  North Maerica  North Maerica     North Maerica  North Maerica   

Address   1056 Sanchez St 551 Alvarado St   My address  
City        San Francisco   San Francisco      My City  
Country               USA             USA  My  Country  
Employees              12              20           10  
ID                      5               6            7  
Name              Sanchez      Richvalley      My Shop  
State          California        CA 94114     My State  
Continent   North Maerica   North Maerica      Content

In [32]:
mydf_t.T

City      Country Employees ID         Name  \
Address                                                                 
3666 21st St     San Francisco          USA         8  1      Madeira   
735 Dolores St   San Francisco          USA        15  2  Bready Shop   
332 Hill St      San Francisco          USA        25  3  Super River   
3995 23rd St     San Francisco          USA        10  4   Ben's Shop   
1056 Sanchez St  San Francisco          USA        12  5      Sanchez   
551 Alvarado St  San Francisco          USA        20  6   Richvalley   
My address             My City  My  Country        10  7      My Shop   

                            State      Continent  
Address                                           
3666 21st St             CA 94114  North Maerica  
735 Dolores St           CA 94119  North Maerica  
332 Hill St      California 94114  North Maerica  
3995 23rd St             CA 94114  North Maerica  
1056 Sanchez St        California  North Maerica  
551 Alvarado St          CA 94114  North Maerica  
My address               My State        Content

In [33]:
pip install geopy

SyntaxError: invalid syntax (<ipython-input-33-4f67b087ebca>, line 1)

In [34]:
import geopy

In [35]:
dir(geopy)

['ArcGIS',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeFarm',
 'GeocoderDotUS',
 'GoogleV3',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'NaviData',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Photon',
 'Point',
 'What3Words',
 'YahooPlaceFinder',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'units',
 'util']

In [36]:
from geopy.geocoders import Nominatim

In [37]:
nom=Nominatim()

In [40]:
n = nom.geocode('2446 HIdden Creek Ave, Thousand Oaks, CA 91360')

In [42]:
n.latitude


34.224435

In [43]:
n.longitude

-118.8952619

In [47]:
import pandas
df = pandas.read_csv('./data/supermarkets.csv')
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [48]:
df['Address'] = df['Address'] + ', ' + df['City']  + ', ' + df['State'] + ', ' + df['Country']
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [49]:
df['Coordinates'] = df['Address'].apply(nom.geocode)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666, 21st Street, Noe Valley, SF, California...  
1                                               None  
2  (332, Hill Street, Noe Valley, SF, California,...  
3  (3995, 23rd Street, Noe Valley, SF, California...  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  
5  (551, Alvarado Street, Noe Valley, SF, Califor...

In [54]:
df['Latitude'] = df['Coordinates'].apply(lambda x: x.latitude if x != None else None)
df['Longitude'] = df['Coordinates'].apply(lambda x: x.longitude if x != None else None)

df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666, 21st Street, Noe Valley, SF, California...  37.756489 -122.429343  
1                                               None        NaN         NaN  
2  (332, Hill Street, Noe Valley, SF, California,...  37.755725 -122.428601  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  37.752146 -122.429815  
5  (551, Alvarado Street, Noe Valley, SF, Califor...  37.753673 -122.433220

In [55]:
import numpy

In [56]:
n = numpy.arange(27)

In [57]:
n


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [58]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [59]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [60]:
n.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [61]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
import cv2

In [68]:
greyimg = cv2.imread('./data/smallgray.png', 0)

In [69]:
greyimg

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [72]:
greyimg[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [73]:
for i in greyimg:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [75]:
for i in greyimg.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [76]:
for i in greyimg.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [78]:
ims = numpy.hstack((greyimg,greyimg))

In [79]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [80]:
vms = numpy.vstack((greyimg,greyimg))

In [81]:
vms

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [83]:
lst = numpy.hsplit(ims,2)

In [84]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]